### ISSUE TITLE
Bug when handling query parameters

### ISSUE THREAD

**Issue by oishikg** [Holmusk/servant-docs-simple#17] opened 2021-08-23 15:54 UTC
I am attempting generate documentation for once of my projects with the following API endpoint: 

```
data MeadowMoodAndJournalingSite route = MeadowMoodAndJournalingSite
  { ... // other endpoints in the same hierarchy
   , mmajsGetEntries :: route
        :- "get-entries"
        :> QueryParam "page-no" Int
        :> QueryParam "search-string" Text
        :> Get '[Proto] Proto.MoodAndJournalEntries
  } deriving stock (Generic)

```

However, the documentation generated is as follows:

```
/api/meadow/mood-journaling/get-entries:
Authentication: MEADOW_SESSION
QueryParam:
    Param: search-string
    ContentType: Text
RequestType: 'GET
Response:
    Format: ': * Proto ('[] *)
    ContentType: MoodAndJournalEntries

```

For some reason, the second query parameter is missed when generating the documentation.

**Comment by jhrcek** [comment] 2021-08-24 05:34
I think the problem is that here:
https://github.com/Holmusk/servant-docs-simple/blob/427028a0553a43c926dfb5078fe87f2bd35a7afc/src/Servant/Docs/Simple/Parse.hs#L220

When you reach the Verb, you create a Map out of `[(Text, Details)]`.
In the case of QueryParam the Text is "QueryParam" coming from https://github.com/Holmusk/servant-docs-simple/blob/427028a0553a43c926dfb5078fe87f2bd35a7afc/src/Servant/Docs/Simple/Parse.hs#L185

But since you can only have **one** value for any key in the map, only one "QueryParam" is kept.
To fix this I'd have to look deeper in how the library works..

**Comment by oishikg** [comment] 2021-08-24 11:36
Thanks for taking a look @jhrcek!

**Comment by turboMaCk** [comment] 2021-09-19 06:49
I think we need to remove the conversions to Map and keep data in list `[(key, val)]`. It will make lookups slower but it's more appropriate representation which won't have this issue.

**Comment by jhrcek** [comment] 2021-09-19 07:08
That was my first thought too. At this point it might be good to also get some feedback from @kwannoel 
Do you remember what was the motivation for using the map in the first place? Was it to make lookups more efficient or was there some other reason?

**Comment by jhrcek** [comment] 2021-09-19 09:24
Here's the experiment with replacing the internal OMap representation with [(key,val)] as suggested by Marek.
https://github.com/Holmusk/servant-docs-simple/pull/21

There's not even any issue with inefficient lookup because we only every convert to/from that map using toList/assoc.

@oishikg it would be nice if you could point me to all holmusk projects where we're using servant-docs-simple so I can test out this change and diff the resulting generated docs.
EDIT: nevermind, I found the usages in CDMP, CDMP-HK and meadow repositories.

**Comment by kwannoel** [comment] 2021-09-19 09:27
> That was my first thought too. At this point it might be good to also get some feedback from @kwannoel
> Do you remember what was the motivation for using the map in the first place? Was it to make lookups more efficient or was there some other reason?

Yeah, it was to make lookups more efficient.
I think lists are fine, maybe run some benchmarks to make sure it doesn't take too long to generate documentation. (Although I think it shouldn't suffer that much, IIRC the bulk of time was for compilation and not runtime).

**Comment by jhrcek** [comment] 2021-09-19 09:55
The efficiency of the implementation should be improved slightly because when using OMap, we would insert the list of pairs into the map using fromList when reaching "end" of each endpoint (the Verb combinator [here](https://github.com/Holmusk/servant-docs-simple/pull/21/files#diff-1254e9869e236acdbe808187c1505abc1208fa27b1bb9322df0988c7c26c2aecL222)). After this PR this step is removed.

The only thing that could potentially cause performance issues is that each of the HasParsableEndpoint instances appends the details to the end of the accumulating list, which leads to quadratic complexity. But that problem existed also in the previous implementation and in practice the length of lists (corresponding to number of combinators in the each api endpoint) will not be more than say 10 - 20. But all of that happens during runtime (when you actually run the Json or Text generating function) and the main source of slowness when using this library will be the compile time.

**Comment by turboMaCk** [comment] 2021-09-19 14:41
Looking around I agree with @jhrcek. The primary performance hit by change of the representation would be in querying by key but this doesn't seem to happen. Actually the overhead of constructing hashmap was likely greater than gains from efficiencies it provides when querying for keys.

There actually doesn't seem to be even single call of `lookup` function in whole codebase.

**Comment by jhrcek** [comment] 2021-09-19 17:17
I was thinking about the motivation behind introducing the OMap representation and I think it was an attempt to improve the slow compilation times. This might have been a misunderstanding about what causes the slowness. It's not bad runtime representation, it's all the type-level computations (resolving of type classes etc.) that is happening at compile time.

**Comment by jhrcek** [comment] 2021-09-21 15:02
Resolved in https://github.com/Holmusk/servant-docs-simple/pull/21

**Closed as completed by jhrcek** 2021-09-21 15:02 UTC
